[plugin]
repository = "https://github.com/Glyceri/TalkCopy.git"
commit = "2c87c668c9c3e13a6bca8619a69063dd6540504a"
owners = ["Glyceri",]
	changelog = """
    [1.2.0.0]
    Now automatically copies the text of tooltips.
    Added a Text Copy Mode. This allows you to copy text from ANY text element on the screen. (Default entry is: 'Ctrl' + 'Shift' + 'Space')
    Text will now properly parse and no longer display '=' from time to time.
    You can now disable metadata in copied text.
"""
