[plugin]
repository = "https://github.com/Glyceri/AcquisitionDate.git"
commit = "e2c8629cf1aaef98ed89fbc1d0007da9ca1dcd74"
owners = ["Glyceri",]
	changelog = """
    [0.1.0.1]
    Shows a couple more warnings and tutorials in the UI for the session token.
    Fixed a bug where disabling the Show Placeholder Dates option would prevent any date from showing up. 
"""
