[plugin]
repository = "https://github.com/Glyceri/AcquisitionDate.git"
commit = "d58089c5009f1e99d8c14eb2422a8f2d0c83da41"
owners = ["Glyceri",]
	changelog = """
    [0.1.1.2]
    Fixes acquisition for users with ' in their name to not work (For real this time c:).
"""
