[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "ab9f0c8a77564e22765c185d128417db2adacbb9"
owners = ["Glyceri"]
	changelog = """
[2.4.0.3] 
- Fixes 2749273439827 bugs that have to do with database entries not existing anymore.
"""
