[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "d52fa637037da090d0a164db531048668e748b0a"
owners = ["Glyceri"]
	changelog = """
    [2.2.0.3]
    Fixed an issue where the Petlist incorrectly thought the selected user was the local user.
    Fixed an issue where users wouldn't transform into IPC users upon receiving IPC data (this clears manual shares unless synced, this is intentional from now on).
    Fixed an issue where users with zero pets would show up in the Petlist. This was impossible to occur before, since the implementation of sync this occurs when someone has zero pets.
"""
