[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "dbcfa944f9e5f5966649b7fa7ecc26ffe53bf1d6"
owners = ["Glyceri"]
	changelog = """
[2.3.0.14]
Fixes a quite common crash.
"""
