[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "cea14d77c3a85b82aa543a93b6816e16b427afa0"
owners = ["Glyceri"]
	changelog = """
    [1.5.0.2]
    Fixed deprecation issue.
    Re-enabled context menus.
"""
