[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "051258454a98afdcd4ede1bd7b840391b6984204"
owners = ["Glyceri"]
	changelog = """
    [2.2.0.2]
    Push from testing to stable.
"""
