[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "3a4edc837e1a698b566d167941ff54e0b1a696d4"
owners = ["Glyceri"]
	changelog = """
[2.4.0.4] 
- Fixes Crashes on the staging branch. (Genuinely only 50% my fault this time c:)
"""
