[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "fffc89b2ce8e4170df13000fe873ab2fb6d9ac9e"
owners = ["Glyceri"]
	changelog = """
[2.6.1.1] 
Added a guard around saving which seems to be failing for unkown reasons.
"""





