[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "901fd921ccdd979ed550c2ece45978224f4f999f"
owners = ["Glyceri"]
	changelog = """
    [2.3.0.12]
    Tentative fix for memory leak.
"""
