[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "1409203f60cd140dfa072e27c88d6d1e95dfba67"
owners = ["Glyceri"]
	changelog = """
    [2.1.2.3]
    Fixes a couple bugs.
    The party list will now refresh in real time when updating names.
"""
