[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "145e825a9174008a87be4bce16f527f3b0cef454"
owners = ["Glyceri"]
	changelog = """
[2.6.1.1] 
Added a guard around saving which seems to be failing for unkown reasons.
"""




