[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "f0c82a9fbea8e9a37fad6383aa262fb2c094ef63"
owners = ["Glyceri"]
	changelog = """
[2.4.0.0]
Stability fixes made by Haselnusbomber
Updated for 7.2
"""
