[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "8be44ac08869b92c1772a01b8f31b2db60e333bd"
owners = ["Glyceri"]
	changelog = """
    [2.3.0.12]
    Tentative fix for memory leak.
"""
