[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "2eb679521828c455b3e487809571741d71923f4f"
owners = ["Glyceri"]
	changelog = """
    [1.5.0.3]
    Fixed the deprecation fix.
"""
