[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "2ba24a8b164dcbe5a71020dd066e8cc9d7e4588d"
owners = ["Glyceri"]
	changelog = """
[2.6.1.0] 
Updated to the latest .pcp implementation.
"""



