[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "0b3cfd08c0c28c6a4fc5fd56e2143366e075b965"
owners = ["Glyceri"]
	changelog = """
[2.6.1.2] 
+ Changed some IPC names.	(If you are a plugin dev that uses the IPC, it should be extremely easy to fix).
"""








