[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "0004819e5f70944cb0c8e9a268af690ae9c9011f"
owners = ["Glyceri",]
	changelog = """
    [2.1.1.0]
    You can now see nicknames on Island Pets.
    (Names wont show in every location, with islands I will take a laid back "if it works it works" approach)
"""
