[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "9c0ac7e1b567d58fc44a6bf0fe044fd6c0e2d27c"
owners = ["Glyceri",]
	changelog = """
    [2.1.1.1]
    Added a config setting for island pets.
    You can now rename from the MJIMinionNoteBook.
"""
