[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "434a39ed97175bd0537500d922070ac55013aa17"
owners = ["Glyceri",]
	changelog = """
    [2.1.1.0]
    You can now see nicknames on Island Pets.
    (Names wont show in every location, with islands I will take a laid back "if it works it works" approach)
"""
