[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "7cce3a497a3d52b1fba0531b1b5d4df1d8f2bc63"
owners = ["Glyceri",]
	changelog = """
    [2.1.1.2]
    Added the pet list button back (I lost it during aetheryte travel... sorry)
"""
