[plugin]
repository = "https://github.com/Glyceri/FFXIVPetRenamer.git"
commit = "2f128810c8a7583dd46bea64890732408c4a90e7"
owners = ["Glyceri",]
	changelog = """
    [2.2.0.0]
    Massive performance increase (This requires the testing branch)
    Nicknames for Tooltips on the (mini)map in alliance raids should now work (probably, I ran like 20 alliance raids, it all looked fine)
    Companion Type images are now also visible in the petlist
    Better refresh on certain elements, namely the party list and tooltips when updated via IPC. (Stuff like target bars will still require you to retarget someone/thing for it to update, sorry)
"""
