[plugin]
repository = "https://github.com/Glyceri/XivFatalFrame.git"
commit = "b41dd9e34f4397f228010f3b2e738e5b7cc782bf"
owners = ["Glyceri",]
	changelog = """
[0.1.0.0] (First Version)
- Take a screenshot every time you die.

(It also takes screenshots upon certain unlocks and completions.)
(This is configurable)
"""
