[plugin]
repository = "https://github.com/Glyceri/XivFatalFrame.git"
commit = "ed321d9b31f6133a028f0d633c11d7f9a388f1e0"
owners = ["Glyceri",]
	changelog = """
[0.1.0.0] (First Version)
- Take a screenshot every time you die.

(It also takes screenshots upon certain unlocks and completions.)
(This is configurable)
"""
