[plugin]
repository = "https://github.com/Glyceri/XivFatalFrame.git"
commit = "95c04c774b8fac57602037f54f1d149b57a7db32"
owners = ["Glyceri",]
	changelog = """
[0.1.1.1]
- Actually updated for 7.2

[0.1.1.0]
- Updated for 7.2

[0.1.0.0] (First Version)
- Take a screenshot every time you die.

(It also takes screenshots upon certain unlocks and completions.)
(This is configurable)
"""
