[plugin]
repository = "https://github.com/Glyceri/XivFatalFrame.git"
commit = "e2f799c9fe0f66b9f964d19f5ebe563c5b5a4e1b"
owners = ["Glyceri",]
	changelog = """
[0.2.0.0]
- You can now set custom delay timers for a screenshot (Some options have pvp specific delays).
- The version number and coffee button should no longer overlap... hopefully
"""
